/**
 * /api/metrics  — Prometheus text format
 *
 * Scraped by Prometheus every 30s (see prometheus.yml job: apex_dashboard).
 * Pulls live values from Redis and exposes them in exposition format.
 *
 * Metrics exposed:
 *   apex_kill_switch_active               gauge  0|1
 *   apex_ensemble_weight{model}           gauge  0.0–1.0
 *   apex_portfolio_daily_pnl_pct          gauge  float
 *   apex_portfolio_cumulative_pnl_pct     gauge  float
 *   apex_active_positions_count           gauge  int
 *   apex_last_signal_timestamp            gauge  unix timestamp
 *   apex_pending_alerts_count             gauge  int
 *   apex_model_sharpe_drift_ratio         gauge  float (from model alerts)
 *   apex_dashboard_up                     gauge  1 (heartbeat)
 *   apex_dashboard_scrape_timestamp       gauge  unix timestamp
 */

import { NextResponse } from "next/server";
import { createClient } from "redis";

export const dynamic = "force-dynamic";

const REDIS_HOST = process.env.REDIS_HOST ?? "localhost";

async function getRedis() {
  const c = createClient({ socket: { host: REDIS_HOST, port: 6379 } });
  await c.connect();
  return c;
}

function metric(name: string, value: number | null, labels?: Record<string, string>, help?: string, type?: string): string {
  if (value === null || isNaN(value)) return "";
  const labelStr = labels
    ? "{" + Object.entries(labels).map(([k, v]) => `${k}="${v}"`).join(",") + "}"
    : "";
  const lines: string[] = [];
  if (help) lines.push(`# HELP ${name} ${help}`);
  if (type) lines.push(`# TYPE ${name} ${type}`);
  lines.push(`${name}${labelStr} ${value}`);
  return lines.join("\n");
}

export async function GET() {
  const lines: string[] = [
    "# APEX Dashboard Metrics — generated by /api/metrics",
    `# Timestamp: ${new Date().toISOString()}`,
    "",
  ];

  // Always-up heartbeat
  lines.push(metric("apex_dashboard_up", 1, undefined, "1 when dashboard is running", "gauge"));
  lines.push(metric("apex_dashboard_scrape_timestamp", Date.now() / 1000, undefined, "Unix timestamp of last scrape", "gauge"));
  lines.push("");

  let r: Awaited<ReturnType<typeof getRedis>> | null = null;
  try {
    r = await getRedis();

    // ── Kill switch ──────────────────────────────────────────────────────────
    const halt = await r.get("apex:kill_switch");
    lines.push(metric("apex_kill_switch_active", halt ? 1 : 0, undefined, "1 when emergency halt is active", "gauge"));
    lines.push("");

    // ── Ensemble weights ─────────────────────────────────────────────────────
    const weightsRaw = await r.get("apex:ensemble:weights");
    if (weightsRaw) {
      const weights = JSON.parse(weightsRaw) as Record<string, number>;
      lines.push("# HELP apex_ensemble_weight Current normalized weight for each ensemble component");
      lines.push("# TYPE apex_ensemble_weight gauge");
      for (const [model, w] of Object.entries(weights)) {
        lines.push(`apex_ensemble_weight{model="${model}"} ${w}`);
      }
      lines.push("");
    }

    // ── Portfolio state ───────────────────────────────────────────────────────
    const portfolioRaw = await r.get("apex:portfolio:state");
    if (portfolioRaw) {
      try {
        const p = JSON.parse(portfolioRaw) as Record<string, unknown>;
        lines.push(metric("apex_portfolio_daily_pnl_pct",        Number(p.daily_pnl_pct)        ?? null, undefined, "Portfolio daily P&L as a fraction", "gauge"));
        lines.push(metric("apex_portfolio_cumulative_pnl_pct",   Number(p.cumulative_pnl_pct)   ?? null, undefined, "Portfolio cumulative P&L as a fraction", "gauge"));
        lines.push(metric("apex_active_positions_count",         Number(p.positions_count)      ?? null, undefined, "Number of open positions", "gauge"));
        lines.push("");
      } catch (_) {}
    }

    // ── Signal pipeline ───────────────────────────────────────────────────────
    const lastSignalRaw = await r.get("apex:signal_engine:last_signal_ts");
    if (lastSignalRaw) {
      lines.push(metric("apex_last_signal_timestamp", Number(lastSignalRaw), undefined, "Unix timestamp of the last signal produced", "gauge"));
      lines.push("");
    }

    // ── Model alerts / drift ──────────────────────────────────────────────────
    const alertsRaw = await r.lRange("apex:model_alerts", 0, 9);
    let   driftRatio: number | null = null;
    let   undismissed = 0;

    for (const a of alertsRaw) {
      try {
        const alert = JSON.parse(a) as Record<string, unknown>;
        if (!alert.dismissed) {
          undismissed++;
          if (alert.type === "MODEL_SHARPE_DRIFT" && typeof alert.drift_ratio === "number") {
            driftRatio = Math.max(driftRatio ?? 0, alert.drift_ratio as number);
          }
        }
      } catch (_) {}
    }

    lines.push(metric("apex_pending_alerts_count",    undismissed, undefined, "Number of undismissed model/risk alerts", "gauge"));
    if (driftRatio !== null) {
      lines.push(metric("apex_model_sharpe_drift_ratio", driftRatio, undefined, "Fraction by which live Sharpe is below backtest baseline", "gauge"));
    }
    lines.push("");

    // ── Live model info ───────────────────────────────────────────────────────
    const liveModelId = await r.get("apex:signal_engine:active_model");
    if (liveModelId) {
      const liveRaw = await r.get(`apex:models:${liveModelId}`);
      if (liveRaw) {
        try {
          const lm = JSON.parse(liveRaw) as Record<string, unknown>;
          lines.push(metric("apex_live_model_val_sharpe",   Number(lm.val_sharpe)   ?? null, undefined, "Validation Sharpe of the currently live model", "gauge"));
          lines.push(metric("apex_live_model_val_hit_rate", Number(lm.val_hit_rate) ?? null, undefined, "Validation hit rate % of the currently live model", "gauge"));
          lines.push("");
        } catch (_) {}
      }
    }

    await r.disconnect();
  } catch (_) {
    if (r) { try { await r.disconnect(); } catch (_2) {} }
    // Redis unavailable — still return heartbeat metrics collected above
  }

  const body = lines.filter((l) => l !== undefined).join("\n") + "\n";

  return new NextResponse(body, {
    status: 200,
    headers: {
      "Content-Type": "text/plain; version=0.0.4; charset=utf-8",
      "Cache-Control": "no-store",
    },
  });
}
